# Nextcloud filter for Fail2Ban
# Place at /etc/fail2ban/filter.d/nextcloud.conf

[Definition]
failregex = ^.*Login failed: .* \(Remote IP: <HOST>\).*$
            ^.*"remoteAddr":"<HOST>".*Trusted domain error.*$
ignoreregex =
